// lib/naics-codes.ts
/**
 * Comprehensive NAICS Codes Reference
 * North American Industry Classification System
 * Used for government contracting and business classification
 */

export interface NAICSCode {
  code: string;
  title: string;
  description?: string;
}

export const NAICS_CODES: NAICSCode[] = [
  // Information Technology & Software (54151X)
  { code: '541511', title: 'Custom Computer Programming Services', description: 'Software development, custom applications' },
  { code: '541512', title: 'Computer Systems Design Services', description: 'IT infrastructure planning and design' },
  { code: '541513', title: 'Computer Facilities Management Services', description: 'On-site management of computer systems' },
  { code: '541519', title: 'Other Computer Related Services', description: 'Computer disaster recovery, software installation' },
  { code: '518210', title: 'Data Processing, Hosting, and Related Services', description: 'Cloud services, web hosting, data centers' },
  { code: '511210', title: 'Software Publishers', description: 'Commercial software development and publishing' },
  { code: '519130', title: 'Internet Publishing and Broadcasting', description: 'Web search portals, internet content providers' },
  
  // Professional Services (5416XX)
  { code: '541611', title: 'Administrative Management Consulting Services', description: 'Business strategy, operations consulting' },
  { code: '541612', title: 'Human Resources Consulting Services', description: 'HR strategy, talent management' },
  { code: '541613', title: 'Marketing Consulting Services', description: 'Market research, brand strategy' },
  { code: '541614', title: 'Process, Physical Distribution, Logistics Consulting', description: 'Supply chain optimization' },
  { code: '541618', title: 'Other Management Consulting Services', description: 'General business consulting' },
  { code: '541690', title: 'Other Scientific and Technical Consulting Services', description: 'Technical advisory services' },
  
  // Engineering Services (5413XX)
  { code: '541310', title: 'Architectural Services', description: 'Building design, architectural planning' },
  { code: '541320', title: 'Landscape Architectural Services', description: 'Landscape design and planning' },
  { code: '541330', title: 'Engineering Services', description: 'Civil, mechanical, electrical engineering' },
  { code: '541340', title: 'Drafting Services', description: 'CAD services, technical drawings' },
  { code: '541350', title: 'Building Inspection Services', description: 'Code compliance, safety inspections' },
  { code: '541360', title: 'Geophysical Surveying and Mapping Services', description: 'Geographic information systems' },
  { code: '541370', title: 'Surveying and Mapping (except Geophysical) Services', description: 'Land surveying, boundary surveys' },
  { code: '541380', title: 'Testing Laboratories', description: 'Quality testing, materials analysis' },
  
  // Research & Development (5417XX)
  { code: '541711', title: 'Research and Development in Biotechnology', description: 'Biotech R&D, genetic research' },
  { code: '541712', title: 'Research and Development in Physical, Engineering, Life Sciences', description: 'Scientific research laboratories' },
  { code: '541713', title: 'Research and Development in Nanotechnology', description: 'Nanotech research and development' },
  { code: '541714', title: 'Research and Development in Biotechnology (except Nanobiotechnology)', description: 'Biological research' },
  { code: '541715', title: 'Research and Development in Physical, Engineering, Life Sciences (except Nano)', description: 'General scientific R&D' },
  { code: '541720', title: 'Research and Development in Social Sciences and Humanities', description: 'Economic, social research' },
  
  // Legal Services (5411XX)
  { code: '541110', title: 'Offices of Lawyers', description: 'Legal services, law firms' },
  { code: '541120', title: 'Offices of Notaries', description: 'Notary public services' },
  { code: '541191', title: 'Title Abstract and Settlement Offices', description: 'Real estate title services' },
  { code: '541199', title: 'All Other Legal Services', description: 'Paralegal, legal support services' },
  
  // Accounting Services (5412XX)
  { code: '541211', title: 'Offices of Certified Public Accountants', description: 'Accounting, auditing, tax preparation' },
  { code: '541213', title: 'Tax Preparation Services', description: 'Individual and business tax services' },
  { code: '541214', title: 'Payroll Services', description: 'Payroll processing and administration' },
  { code: '541219', title: 'Other Accounting Services', description: 'Bookkeeping, financial consulting' },
  
  // Design Services (5414XX)
  { code: '541410', title: 'Interior Design Services', description: 'Interior space planning and design' },
  { code: '541420', title: 'Industrial Design Services', description: 'Product design, industrial aesthetics' },
  { code: '541430', title: 'Graphic Design Services', description: 'Visual design, branding' },
  { code: '541490', title: 'Other Specialized Design Services', description: 'Fashion, textile, set design' },
  
  // Marketing & Advertising (5418XX)
  { code: '541810', title: 'Advertising Agencies', description: 'Full-service advertising' },
  { code: '541820', title: 'Public Relations Agencies', description: 'PR, media relations, crisis management' },
  { code: '541830', title: 'Media Buying Agencies', description: 'Media planning and purchasing' },
  { code: '541840', title: 'Media Representatives', description: 'Media sales representation' },
  { code: '541850', title: 'Indoor and Outdoor Display Advertising', description: 'Billboard, display advertising' },
  { code: '541860', title: 'Direct Mail Advertising', description: 'Direct marketing services' },
  { code: '541870', title: 'Advertising Material Distribution Services', description: 'Flyer distribution, sampling' },
  { code: '541890', title: 'Other Services Related to Advertising', description: 'Advertising consulting' },
  
  // Market Research (5419XX)
  { code: '541910', title: 'Marketing Research and Public Opinion Polling', description: 'Market analysis, surveys' },
  { code: '541920', title: 'Photographic Services', description: 'Commercial photography' },
  { code: '541930', title: 'Translation and Interpretation Services', description: 'Language services' },
  { code: '541940', title: 'Veterinary Services', description: 'Animal healthcare' },
  { code: '541990', title: 'All Other Professional, Scientific, and Technical Services', description: 'Miscellaneous professional services' },
  
  // Administrative Support (5611XX)
  { code: '561110', title: 'Office Administrative Services', description: 'Office management, administrative support' },
  { code: '561210', title: 'Facilities Support Services', description: 'Facility operations and maintenance' },
  { code: '561311', title: 'Employment Placement Agencies', description: 'Recruiting, staffing services' },
  { code: '561312', title: 'Executive Search Services', description: 'Executive recruiting, headhunting' },
  { code: '561320', title: 'Temporary Help Services', description: 'Temp staffing, contract labor' },
  { code: '561330', title: 'Professional Employer Organizations', description: 'HR outsourcing, PEO services' },
  
  // Business Support Services (5614XX)
  { code: '561410', title: 'Document Preparation Services', description: 'Typing, word processing, transcription' },
  { code: '561421', title: 'Telephone Answering Services', description: 'Call center services' },
  { code: '561422', title: 'Telemarketing Bureaus and Other Contact Centers', description: 'Outbound calling, customer service' },
  { code: '561431', title: 'Private Mail Centers', description: 'Mailbox rental, shipping services' },
  { code: '561439', title: 'Other Business Service Centers', description: 'Copy shops, business centers' },
  { code: '561440', title: 'Collection Agencies', description: 'Debt collection services' },
  { code: '561450', title: 'Credit Bureaus', description: 'Credit reporting, credit checks' },
  { code: '561490', title: 'Other Business Support Services', description: 'Court reporting, repossession' },
  { code: '561491', title: 'Repossession Services', description: 'Asset recovery' },
  { code: '561492', title: 'Court Reporting and Stenotype Services', description: 'Legal transcription' },
  { code: '561499', title: 'All Other Business Support Services', description: 'Miscellaneous business support' },
  
  // Travel Services (5615XX)
  { code: '561510', title: 'Travel Agencies', description: 'Travel booking, vacation planning' },
  { code: '561520', title: 'Tour Operators', description: 'Tour packages, guided tours' },
  { code: '561591', title: 'Convention and Visitors Bureaus', description: 'Tourism promotion' },
  { code: '561599', title: 'All Other Travel Arrangement and Reservation Services', description: 'Travel support services' },
  
  // Security Services (5616XX)
  { code: '561611', title: 'Investigation Services', description: 'Private investigation, background checks' },
  { code: '561612', title: 'Security Guards and Patrol Services', description: 'Security personnel, armed guards' },
  { code: '561613', title: 'Armored Car Services', description: 'Secure transport, cash handling' },
  { code: '561621', title: 'Security Systems Services (except Locksmiths)', description: 'Alarm systems, surveillance' },
  { code: '561622', title: 'Locksmiths', description: 'Lock installation, key duplication' },
  
  // Facilities Services (5617XX)
  { code: '561710', title: 'Exterminating and Pest Control Services', description: 'Pest management' },
  { code: '561720', title: 'Janitorial Services', description: 'Cleaning, custodial services' },
  { code: '561730', title: 'Landscaping Services', description: 'Grounds maintenance, lawn care' },
  { code: '561740', title: 'Carpet and Upholstery Cleaning Services', description: 'Professional cleaning' },
  { code: '561790', title: 'Other Services to Buildings and Dwellings', description: 'Window cleaning, chimney sweeping' },
  
  // Other Support Services (5619XX)
  { code: '561910', title: 'Packaging and Labeling Services', description: 'Product packaging, labeling' },
  { code: '561920', title: 'Convention and Trade Show Organizers', description: 'Event planning, trade shows' },
  { code: '561990', title: 'All Other Support Services', description: 'Miscellaneous support services' },
  
  // Waste Management (562XXX)
  { code: '562111', title: 'Solid Waste Collection', description: 'Garbage collection, waste pickup' },
  { code: '562112', title: 'Hazardous Waste Collection', description: 'Hazmat collection and transport' },
  { code: '562119', title: 'Other Waste Collection', description: 'Recycling collection' },
  { code: '562211', title: 'Hazardous Waste Treatment and Disposal', description: 'Hazmat processing' },
  { code: '562212', title: 'Solid Waste Landfill', description: 'Landfill operations' },
  { code: '562213', title: 'Solid Waste Combustors and Incinerators', description: 'Waste incineration' },
  { code: '562219', title: 'Other Nonhazardous Waste Treatment and Disposal', description: 'Waste processing' },
  { code: '562910', title: 'Remediation Services', description: 'Environmental cleanup, site remediation' },
  { code: '562920', title: 'Materials Recovery Facilities', description: 'Recycling facilities' },
  { code: '562991', title: 'Septic Tank and Related Services', description: 'Septic pumping, maintenance' },
  { code: '562998', title: 'All Other Miscellaneous Waste Management Services', description: 'Other waste services' },
  
  // Education Services (611XXX)
  { code: '611110', title: 'Elementary and Secondary Schools', description: 'K-12 education' },
  { code: '611210', title: 'Junior Colleges', description: 'Community colleges' },
  { code: '611310', title: 'Colleges, Universities, and Professional Schools', description: 'Higher education institutions' },
  { code: '611410', title: 'Business and Secretarial Schools', description: 'Business education' },
  { code: '611420', title: 'Computer Training', description: 'IT training, software education' },
  { code: '611430', title: 'Professional and Management Development Training', description: 'Executive education, professional development' },
  { code: '611511', title: 'Cosmetology and Barber Schools', description: 'Beauty education' },
  { code: '611512', title: 'Flight Training', description: 'Aviation training' },
  { code: '611513', title: 'Apprenticeship Training', description: 'Trade apprenticeships' },
  { code: '611519', title: 'Other Technical and Trade Schools', description: 'Vocational training' },
  { code: '611610', title: 'Fine Arts Schools', description: 'Arts education' },
  { code: '611620', title: 'Sports and Recreation Instruction', description: 'Sports coaching, recreation programs' },
  { code: '611630', title: 'Language Schools', description: 'Language instruction' },
  { code: '611691', title: 'Exam Preparation and Tutoring', description: 'Test prep, tutoring services' },
  { code: '611692', title: 'Automobile Driving Schools', description: 'Driver education' },
  { code: '611699', title: 'All Other Miscellaneous Schools and Instruction', description: 'Other educational services' },
  { code: '611710', title: 'Educational Support Services', description: 'Educational consulting, curriculum development' },
  
  // Healthcare Services (621XXX-623XXX)
  { code: '621111', title: 'Offices of Physicians (except Mental Health)', description: 'Medical practices' },
  { code: '621112', title: 'Offices of Physicians, Mental Health Specialists', description: 'Psychiatrists' },
  { code: '621210', title: 'Offices of Dentists', description: 'Dental practices' },
  { code: '621310', title: 'Offices of Chiropractors', description: 'Chiropractic care' },
  { code: '621320', title: 'Offices of Optometrists', description: 'Eye care' },
  { code: '621330', title: 'Offices of Mental Health Practitioners (except Physicians)', description: 'Counseling, therapy' },
  { code: '621340', title: 'Offices of Physical, Occupational and Speech Therapists', description: 'Rehabilitation services' },
  { code: '621391', title: 'Offices of Podiatrists', description: 'Foot care' },
  { code: '621399', title: 'Offices of All Other Miscellaneous Health Practitioners', description: 'Alternative medicine' },
  { code: '621410', title: 'Family Planning Centers', description: 'Reproductive health services' },
  { code: '621420', title: 'Outpatient Mental Health and Substance Abuse Centers', description: 'Counseling centers' },
  { code: '621491', title: 'HMO Medical Centers', description: 'Health maintenance organizations' },
  { code: '621492', title: 'Kidney Dialysis Centers', description: 'Dialysis services' },
  { code: '621493', title: 'Freestanding Ambulatory Surgical and Emergency Centers', description: 'Outpatient surgery' },
  { code: '621498', title: 'All Other Outpatient Care Centers', description: 'Urgent care, walk-in clinics' },
  { code: '621511', title: 'Medical Laboratories', description: 'Clinical labs, diagnostic testing' },
  { code: '621512', title: 'Diagnostic Imaging Centers', description: 'MRI, X-ray, CT scan facilities' },
  { code: '621610', title: 'Home Health Care Services', description: 'In-home medical care' },
  { code: '621910', title: 'Ambulance Services', description: 'Emergency medical transport' },
  { code: '621991', title: 'Blood and Organ Banks', description: 'Blood donation, organ procurement' },
  { code: '621999', title: 'All Other Miscellaneous Ambulatory Health Care Services', description: 'Other healthcare' },
  { code: '622110', title: 'General Medical and Surgical Hospitals', description: 'Hospital facilities' },
  { code: '622210', title: 'Psychiatric and Substance Abuse Hospitals', description: 'Mental health hospitals' },
  { code: '622310', title: 'Specialty (except Psychiatric and Substance Abuse) Hospitals', description: 'Specialty care hospitals' },
  { code: '623110', title: 'Nursing Care Facilities (Skilled Nursing Facilities)', description: 'Long-term care' },
  { code: '623210', title: 'Residential Intellectual and Developmental Disability Facilities', description: 'Group homes' },
  { code: '623220', title: 'Residential Mental Health and Substance Abuse Facilities', description: 'Residential treatment' },
  { code: '623311', title: 'Continuing Care Retirement Communities', description: 'Senior living communities' },
  { code: '623312', title: 'Assisted Living Facilities for the Elderly', description: 'Assisted living' },
  { code: '624110', title: 'Child and Youth Services', description: 'Youth programs, foster care' },
  { code: '624120', title: 'Services for the Elderly and Persons with Disabilities', description: 'Senior services, disability support' },
  { code: '624190', title: 'Other Individual and Family Services', description: 'Social services' },
  { code: '624210', title: 'Community Food Services', description: 'Food banks, soup kitchens' },
  { code: '624221', title: 'Temporary Shelters', description: 'Emergency shelters' },
  { code: '624229', title: 'Other Community Housing Services', description: 'Transitional housing' },
  { code: '624230', title: 'Emergency and Other Relief Services', description: 'Disaster relief' },
  { code: '624310', title: 'Vocational Rehabilitation Services', description: 'Job training for disabled' },
  { code: '624410', title: 'Child Day Care Services', description: 'Childcare centers' },
  
  // Construction (236XXX-238XXX)
  { code: '236115', title: 'New Single-Family Housing Construction', description: 'Residential home building' },
  { code: '236116', title: 'New Multifamily Housing Construction', description: 'Apartment building construction' },
  { code: '236117', title: 'New Housing For-Sale Builders', description: 'Spec home builders' },
  { code: '236118', title: 'Residential Remodelers', description: 'Home renovation' },
  { code: '236210', title: 'Industrial Building Construction', description: 'Factory, warehouse construction' },
  { code: '236220', title: 'Commercial and Institutional Building Construction', description: 'Office buildings, schools, hospitals' },
  { code: '237110', title: 'Water and Sewer Line and Related Structures Construction', description: 'Utility infrastructure' },
  { code: '237120', title: 'Oil and Gas Pipeline and Related Structures Construction', description: 'Energy infrastructure' },
  { code: '237130', title: 'Power and Communication Line and Related Structures Construction', description: 'Power lines, telecom infrastructure' },
  { code: '237210', title: 'Land Subdivision', description: 'Land development' },
  { code: '237310', title: 'Highway, Street, and Bridge Construction', description: 'Road construction' },
  { code: '237990', title: 'Other Heavy and Civil Engineering Construction', description: 'Dams, tunnels, marine construction' },
  { code: '238110', title: 'Poured Concrete Foundation and Structure Contractors', description: 'Concrete work' },
  { code: '238120', title: 'Structural Steel and Precast Concrete Contractors', description: 'Steel erection' },
  { code: '238130', title: 'Framing Contractors', description: 'Wood framing' },
  { code: '238140', title: 'Masonry Contractors', description: 'Brick, stone, concrete masonry' },
  { code: '238150', title: 'Glass and Glazing Contractors', description: 'Window installation' },
  { code: '238160', title: 'Roofing Contractors', description: 'Roof installation and repair' },
  { code: '238170', title: 'Siding Contractors', description: 'Exterior siding installation' },
  { code: '238190', title: 'Other Foundation, Structure, and Building Exterior Contractors', description: 'Exterior construction' },
  { code: '238210', title: 'Electrical Contractors and Other Wiring Installation Contractors', description: 'Electrical work' },
  { code: '238220', title: 'Plumbing, Heating, and Air-Conditioning Contractors', description: 'HVAC, plumbing' },
  { code: '238290', title: 'Other Building Equipment Contractors', description: 'Elevator installation, fire protection' },
  { code: '238310', title: 'Drywall and Insulation Contractors', description: 'Interior finishing' },
  { code: '238320', title: 'Painting and Wall Covering Contractors', description: 'Painting services' },
  { code: '238330', title: 'Flooring Contractors', description: 'Floor installation' },
  { code: '238340', title: 'Tile and Terrazzo Contractors', description: 'Tile work' },
  { code: '238350', title: 'Finish Carpentry Contractors', description: 'Trim, cabinets' },
  { code: '238390', title: 'Other Building Finishing Contractors', description: 'Interior finishing' },
  { code: '238910', title: 'Site Preparation Contractors', description: 'Excavation, grading' },
  { code: '238990', title: 'All Other Specialty Trade Contractors', description: 'Miscellaneous construction' },
  
  // Manufacturing (3XXXXX)
  { code: '311111', title: 'Dog and Cat Food Manufacturing', description: 'Pet food production' },
  { code: '311119', title: 'Other Animal Food Manufacturing', description: 'Livestock feed' },
  { code: '311211', title: 'Flour Milling', description: 'Grain milling' },
  { code: '311221', title: 'Wet Corn Milling', description: 'Corn processing' },
  { code: '311230', title: 'Breakfast Cereal Manufacturing', description: 'Cereal production' },
  { code: '311330', title: 'Confectionery Manufacturing from Purchased Chocolate', description: 'Chocolate products' },
  { code: '311340', title: 'Nonchocolate Confectionery Manufacturing', description: 'Candy production' },
  { code: '311411', title: 'Frozen Fruit, Juice, and Vegetable Manufacturing', description: 'Frozen food processing' },
  { code: '311412', title: 'Frozen Specialty Food Manufacturing', description: 'Frozen meals' },
  { code: '311421', title: 'Fruit and Vegetable Canning', description: 'Canned goods' },
  { code: '311422', title: 'Specialty Canning', description: 'Pickles, sauces' },
  { code: '311423', title: 'Dried and Dehydrated Food Manufacturing', description: 'Dried foods' },
  { code: '311511', title: 'Fluid Milk Manufacturing', description: 'Dairy processing' },
  { code: '311512', title: 'Creamery Butter Manufacturing', description: 'Butter production' },
  { code: '311513', title: 'Cheese Manufacturing', description: 'Cheese production' },
  { code: '311514', title: 'Dry, Condensed, and Evaporated Dairy Product Manufacturing', description: 'Powdered milk' },
  { code: '311520', title: 'Ice Cream and Frozen Dessert Manufacturing', description: 'Ice cream production' },
  { code: '311611', title: 'Animal (except Poultry) Slaughtering', description: 'Meat processing' },
  { code: '311612', title: 'Meat Processed from Carcasses', description: 'Meat cutting' },
  { code: '311613', title: 'Rendering and Meat Byproduct Processing', description: 'Meat byproducts' },
  { code: '311615', title: 'Poultry Processing', description: 'Poultry slaughtering' },
  { code: '311710', title: 'Seafood Product Preparation and Packaging', description: 'Seafood processing' },
  { code: '311811', title: 'Retail Bakeries', description: 'In-store bakeries' },
  { code: '311812', title: 'Commercial Bakeries', description: 'Wholesale bakeries' },
  { code: '311813', title: 'Frozen Cakes, Pies, and Other Pastries Manufacturing', description: 'Frozen baked goods' },
  { code: '311821', title: 'Cookie and Cracker Manufacturing', description: 'Cookie production' },
  { code: '311824', title: 'Dry Pasta, Dough, and Flour Mixes Manufacturing', description: 'Pasta production' },
  { code: '311830', title: 'Tortilla Manufacturing', description: 'Tortilla production' },
  { code: '311911', title: 'Roasted Nuts and Peanut Butter Manufacturing', description: 'Nut processing' },
  { code: '311919', title: 'Other Snack Food Manufacturing', description: 'Chips, snacks' },
  { code: '311920', title: 'Coffee and Tea Manufacturing', description: 'Beverage processing' },
  { code: '311930', title: 'Flavoring Syrup and Concentrate Manufacturing', description: 'Flavorings' },
  { code: '311941', title: 'Mayonnaise, Dressing, and Other Prepared Sauce Manufacturing', description: 'Condiments' },
  { code: '311942', title: 'Spice and Extract Manufacturing', description: 'Spices' },
  { code: '311991', title: 'Perishable Prepared Food Manufacturing', description: 'Ready-to-eat foods' },
  { code: '311999', title: 'All Other Miscellaneous Food Manufacturing', description: 'Other food products' },
  { code: '312111', title: 'Soft Drink Manufacturing', description: 'Soda production' },
  { code: '312112', title: 'Bottled Water Manufacturing', description: 'Bottled water' },
  { code: '312113', title: 'Ice Manufacturing', description: 'Ice production' },
  { code: '312120', title: 'Breweries', description: 'Beer brewing' },
  { code: '312130', title: 'Wineries', description: 'Wine production' },
  { code: '312140', title: 'Distilleries', description: 'Spirits production' },
  { code: '312230', title: 'Tobacco Manufacturing', description: 'Cigarettes, cigars' },
  
  // Telecommunications (517XXX)
  { code: '517311', title: 'Wired Telecommunications Carriers', description: 'Landline, cable, internet providers' },
  { code: '517312', title: 'Wireless Telecommunications Carriers (except Satellite)', description: 'Cell phone carriers' },
  { code: '517410', title: 'Satellite Telecommunications', description: 'Satellite communication services' },
  { code: '517911', title: 'Telecommunications Resellers', description: 'MVNO, telecom resellers' },
  { code: '517919', title: 'All Other Telecommunications', description: 'Other telecom services' },
  
  // Transportation (48XXXX-49XXXX)
  { code: '481111', title: 'Scheduled Passenger Air Transportation', description: 'Airlines' },
  { code: '481112', title: 'Scheduled Freight Air Transportation', description: 'Air cargo' },
  { code: '481211', title: 'Nonscheduled Chartered Passenger Air Transportation', description: 'Charter flights' },
  { code: '481212', title: 'Nonscheduled Chartered Freight Air Transportation', description: 'Charter cargo' },
  { code: '481219', title: 'Other Nonscheduled Air Transportation', description: 'Sightseeing flights' },
  { code: '482111', title: 'Line-Haul Railroads', description: 'Freight rail' },
  { code: '483111', title: 'Deep Sea Freight Transportation', description: 'Ocean shipping' },
  { code: '483112', title: 'Deep Sea Passenger Transportation', description: 'Cruise lines' },
  { code: '484110', title: 'General Freight Trucking, Local', description: 'Local trucking' },
  { code: '484121', title: 'General Freight Trucking, Long-Distance, Truckload', description: 'Long-haul trucking' },
  { code: '484122', title: 'General Freight Trucking, Long-Distance, Less Than Truckload', description: 'LTL carriers' },
  { code: '484210', title: 'Used Household and Office Goods Moving', description: 'Moving companies' },
  { code: '484220', title: 'Specialized Freight (except Used Goods) Trucking, Local', description: 'Specialty hauling' },
  { code: '484230', title: 'Specialized Freight (except Used Goods) Trucking, Long-Distance', description: 'Specialty long-haul' },
  { code: '485111', title: 'Mixed Mode Transit Systems', description: 'Public transit' },
  { code: '485112', title: 'Commuter Rail Systems', description: 'Commuter rail' },
  { code: '485113', title: 'Bus and Other Motor Vehicle Transit Systems', description: 'Bus transit' },
  { code: '485210', title: 'Interurban and Rural Bus Transportation', description: 'Intercity bus' },
  { code: '485310', title: 'Taxi Service', description: 'Taxi, rideshare' },
  { code: '485320', title: 'Limousine Service', description: 'Limo services' },
  { code: '485410', title: 'School and Employee Bus Transportation', description: 'School buses' },
  { code: '485510', title: 'Charter Bus Industry', description: 'Charter buses' },
  { code: '485991', title: 'Special Needs Transportation', description: 'Medical transport' },
  { code: '485999', title: 'All Other Transit and Ground Passenger Transportation', description: 'Other ground transport' },
  { code: '486110', title: 'Pipeline Transportation of Crude Oil', description: 'Oil pipelines' },
  { code: '486210', title: 'Pipeline Transportation of Natural Gas', description: 'Gas pipelines' },
  { code: '486910', title: 'Pipeline Transportation of Refined Petroleum Products', description: 'Fuel pipelines' },
  { code: '486990', title: 'All Other Pipeline Transportation', description: 'Other pipeline transport' },
  { code: '487110', title: 'Scenic and Sightseeing Transportation, Land', description: 'Tour buses' },
  { code: '487210', title: 'Scenic and Sightseeing Transportation, Water', description: 'Tour boats' },
  { code: '487990', title: 'Scenic and Sightseeing Transportation, Other', description: 'Helicopter tours' },
  { code: '488111', title: 'Air Traffic Control', description: 'ATC services' },
  { code: '488119', title: 'Other Airport Operations', description: 'Airport management' },
  { code: '488190', title: 'Other Support Activities for Air Transportation', description: 'Ground handling' },
  { code: '488210', title: 'Support Activities for Rail Transportation', description: 'Rail services' },
  { code: '488310', title: 'Port and Harbor Operations', description: 'Port operations' },
  { code: '488320', title: 'Marine Cargo Handling', description: 'Cargo loading' },
  { code: '488330', title: 'Navigational Services to Shipping', description: 'Marine navigation' },
  { code: '488390', title: 'Other Support Activities for Water Transportation', description: 'Marine services' },
  { code: '488410', title: 'Motor Vehicle Towing', description: 'Tow truck services' },
  { code: '488490', title: 'Other Support Activities for Road Transportation', description: 'Truck stops' },
  { code: '488510', title: 'Freight Transportation Arrangement', description: 'Freight forwarding, logistics' },
  { code: '488991', title: 'Packing and Crating', description: 'Packaging services' },
  { code: '488999', title: 'All Other Support Activities for Transportation', description: 'Other transport support' },
  { code: '491110', title: 'Postal Service', description: 'Mail delivery' },
  { code: '492110', title: 'Couriers and Express Delivery Services', description: 'Package delivery' },
  { code: '492210', title: 'Local Messengers and Local Delivery', description: 'Local courier' },
  { code: '493110', title: 'General Warehousing and Storage', description: 'Warehouse facilities' },
  { code: '493120', title: 'Refrigerated Warehousing and Storage', description: 'Cold storage' },
  { code: '493130', title: 'Farm Product Warehousing and Storage', description: 'Grain storage' },
  { code: '493190', title: 'Other Warehousing and Storage', description: 'Specialty storage' },
  
  // Retail Trade (44XXXX-45XXXX)
  { code: '441110', title: 'New Car Dealers', description: 'Auto dealerships' },
  { code: '441120', title: 'Used Car Dealers', description: 'Used car sales' },
  { code: '441210', title: 'Recreational Vehicle Dealers', description: 'RV sales' },
  { code: '441222', title: 'Boat Dealers', description: 'Boat sales' },
  { code: '441228', title: 'Motorcycle, ATV, and All Other Motor Vehicle Dealers', description: 'Powersports dealers' },
  { code: '441310', title: 'Automotive Parts and Accessories Stores', description: 'Auto parts stores' },
  { code: '441320', title: 'Tire Dealers', description: 'Tire sales and service' },
  { code: '442110', title: 'Furniture Stores', description: 'Furniture retail' },
  { code: '442210', title: 'Floor Covering Stores', description: 'Flooring retail' },
  { code: '442291', title: 'Window Treatment Stores', description: 'Blinds, curtains' },
  { code: '442299', title: 'All Other Home Furnishings Stores', description: 'Home décor' },
  { code: '443141', title: 'Household Appliance Stores', description: 'Appliance retail' },
  { code: '443142', title: 'Electronics Stores', description: 'Consumer electronics' },
  { code: '444110', title: 'Home Centers', description: 'Hardware stores' },
  { code: '444120', title: 'Paint and Wallpaper Stores', description: 'Paint stores' },
  { code: '444130', title: 'Hardware Stores', description: 'Hardware retail' },
  { code: '444190', title: 'Other Building Material Dealers', description: 'Building materials' },
  { code: '444210', title: 'Outdoor Power Equipment Stores', description: 'Lawn equipment' },
  { code: '444220', title: 'Nursery, Garden Center, and Farm Supply Stores', description: 'Garden centers' },
  { code: '445110', title: 'Supermarkets and Other Grocery (except Convenience) Stores', description: 'Grocery stores' },
  { code: '445120', title: 'Convenience Stores', description: 'Convenience retail' },
  { code: '445210', title: 'Meat Markets', description: 'Butcher shops' },
  { code: '445220', title: 'Fish and Seafood Markets', description: 'Seafood retail' },
  { code: '445230', title: 'Fruit and Vegetable Markets', description: 'Produce markets' },
  { code: '445291', title: 'Baked Goods Stores', description: 'Bakeries' },
  { code: '445292', title: 'Confectionery and Nut Stores', description: 'Candy shops' },
  { code: '445299', title: 'All Other Specialty Food Stores', description: 'Specialty food retail' },
  { code: '445310', title: 'Beer, Wine, and Liquor Stores', description: 'Liquor stores' },
  { code: '446110', title: 'Pharmacies and Drug Stores', description: 'Pharmacies' },
  { code: '446120', title: 'Cosmetics, Beauty Supplies, and Perfume Stores', description: 'Beauty supply stores' },
  { code: '446130', title: 'Optical Goods Stores', description: 'Eyewear retail' },
  { code: '446191', title: 'Food (Health) Supplement Stores', description: 'Vitamin shops' },
  { code: '446199', title: 'All Other Health and Personal Care Stores', description: 'Health retail' },
  { code: '447110', title: 'Gasoline Stations with Convenience Stores', description: 'Gas stations' },
  { code: '447190', title: 'Other Gasoline Stations', description: 'Fuel retail' },
  { code: '448110', title: 'Men\'s Clothing Stores', description: 'Men\'s apparel' },
  { code: '448120', title: 'Women\'s Clothing Stores', description: 'Women\'s apparel' },
  { code: '448130', title: 'Children\'s and Infants\' Clothing Stores', description: 'Kids\' apparel' },
  { code: '448140', title: 'Family Clothing Stores', description: 'Family apparel' },
  { code: '448150', title: 'Clothing Accessories Stores', description: 'Accessories retail' },
  { code: '448190', title: 'Other Clothing Stores', description: 'Specialty apparel' },
  { code: '448210', title: 'Shoe Stores', description: 'Footwear retail' },
  { code: '448310', title: 'Jewelry Stores', description: 'Jewelry retail' },
  { code: '448320', title: 'Luggage and Leather Goods Stores', description: 'Leather goods' },
  { code: '451110', title: 'Sporting Goods Stores', description: 'Sports equipment' },
  { code: '451120', title: 'Hobby, Toy, and Game Stores', description: 'Toy stores' },
  { code: '451130', title: 'Sewing, Needlework, and Piece Goods Stores', description: 'Fabric stores' },
  { code: '451140', title: 'Musical Instrument and Supplies Stores', description: 'Music stores' },
  { code: '451211', title: 'Book Stores', description: 'Bookstores' },
  { code: '451212', title: 'News Dealers and Newsstands', description: 'Newsstands' },
  { code: '452210', title: 'Department Stores', description: 'Department stores' },
  { code: '452311', title: 'Warehouse Clubs and Supercenters', description: 'Warehouse retail' },
  { code: '452319', title: 'All Other General Merchandise Stores', description: 'General retail' },
  { code: '453110', title: 'Florists', description: 'Flower shops' },
  { code: '453210', title: 'Office Supplies and Stationery Stores', description: 'Office supply stores' },
  { code: '453220', title: 'Gift, Novelty, and Souvenir Stores', description: 'Gift shops' },
  { code: '453310', title: 'Used Merchandise Stores', description: 'Thrift stores, consignment' },
  { code: '453910', title: 'Pet and Pet Supplies Stores', description: 'Pet stores' },
  { code: '453920', title: 'Art Dealers', description: 'Art galleries' },
  { code: '453930', title: 'Manufactured (Mobile) Home Dealers', description: 'Mobile home sales' },
  { code: '453991', title: 'Tobacco Stores', description: 'Tobacco shops' },
  { code: '453998', title: 'All Other Miscellaneous Store Retailers (except Tobacco Stores)', description: 'Other retail' },
  { code: '454110', title: 'Electronic Shopping and Mail-Order Houses', description: 'E-commerce' },
  { code: '454210', title: 'Vending Machine Operators', description: 'Vending machines' },
  { code: '454310', title: 'Fuel Dealers', description: 'Heating oil, propane dealers' },
  { code: '454390', title: 'Other Direct Selling Establishments', description: 'Direct sales' },
  
  // Finance & Insurance (52XXXX)
  { code: '522110', title: 'Commercial Banking', description: 'Banks, commercial lending' },
  { code: '522120', title: 'Savings Institutions', description: 'Savings banks, credit unions' },
  { code: '522130', title: 'Credit Unions', description: 'Member-owned credit unions' },
  { code: '522190', title: 'Other Depository Credit Intermediation', description: 'Other banking' },
  { code: '522210', title: 'Credit Card Issuing', description: 'Credit card companies' },
  { code: '522220', title: 'Sales Financing', description: 'Auto financing, appliance financing' },
  { code: '522291', title: 'Consumer Lending', description: 'Personal loans' },
  { code: '522292', title: 'Real Estate Credit', description: 'Mortgage lenders' },
  { code: '522293', title: 'International Trade Financing', description: 'Trade finance' },
  { code: '522294', title: 'Secondary Market Financing', description: 'Loan servicing' },
  { code: '522298', title: 'All Other Nondepository Credit Intermediation', description: 'Other lending' },
  { code: '522310', title: 'Mortgage and Nonmortgage Loan Brokers', description: 'Loan brokerage' },
  { code: '522320', title: 'Financial Transactions Processing, Reserve, and Clearinghouse Activities', description: 'Payment processing' },
  { code: '522390', title: 'Other Activities Related to Credit Intermediation', description: 'Other credit services' },
  { code: '523110', title: 'Investment Banking and Securities Dealing', description: 'Investment banks' },
  { code: '523120', title: 'Securities Brokerage', description: 'Stock brokers' },
  { code: '523130', title: 'Commodity Contracts Dealing', description: 'Futures trading' },
  { code: '523140', title: 'Commodity Contracts Brokerage', description: 'Commodity brokers' },
  { code: '523210', title: 'Securities and Commodity Exchanges', description: 'Stock exchanges' },
  { code: '523910', title: 'Miscellaneous Intermediation', description: 'Financial intermediaries' },
  { code: '523920', title: 'Portfolio Management', description: 'Investment management' },
  { code: '523930', title: 'Investment Advice', description: 'Financial advisors' },
  { code: '523991', title: 'Trust, Fiduciary, and Custody Activities', description: 'Trust services' },
  { code: '523999', title: 'Miscellaneous Financial Investment Activities', description: 'Other investment services' },
  { code: '524113', title: 'Direct Life Insurance Carriers', description: 'Life insurance companies' },
  { code: '524114', title: 'Direct Health and Medical Insurance Carriers', description: 'Health insurance' },
  { code: '524126', title: 'Direct Property and Casualty Insurance Carriers', description: 'Auto, home insurance' },
  { code: '524127', title: 'Direct Title Insurance Carriers', description: 'Title insurance' },
  { code: '524128', title: 'Other Direct Insurance (except Life, Health, and Medical) Carriers', description: 'Specialty insurance' },
  { code: '524130', title: 'Reinsurance Carriers', description: 'Reinsurance companies' },
  { code: '524210', title: 'Insurance Agencies and Brokerages', description: 'Insurance agents' },
  { code: '524291', title: 'Claims Adjusting', description: 'Insurance claims' },
  { code: '524292', title: 'Third Party Administration of Insurance and Pension Funds', description: 'TPA services' },
  { code: '524298', title: 'All Other Insurance Related Activities', description: 'Other insurance services' },
  { code: '525110', title: 'Pension Funds', description: 'Retirement funds' },
  { code: '525120', title: 'Health and Welfare Funds', description: 'Benefit funds' },
  { code: '525190', title: 'Other Insurance Funds', description: 'Other insurance funds' },
  { code: '525910', title: 'Open-End Investment Funds', description: 'Mutual funds' },
  { code: '525920', title: 'Trusts, Estates, and Agency Accounts', description: 'Estate management' },
  { code: '525990', title: 'Other Financial Vehicles', description: 'REITs, investment trusts' },
  
  // Real Estate (531XXX)
  { code: '531110', title: 'Lessors of Residential Buildings and Dwellings', description: 'Apartment rentals, property management' },
  { code: '531120', title: 'Lessors of Nonresidential Buildings (except Miniwarehouses)', description: 'Commercial property rentals' },
  { code: '531130', title: 'Lessors of Miniwarehouses and Self-Storage Units', description: 'Storage facilities' },
  { code: '531190', title: 'Lessors of Other Real Estate Property', description: 'Land rentals' },
  { code: '531210', title: 'Offices of Real Estate Agents and Brokers', description: 'Real estate brokers' },
  { code: '531311', title: 'Residential Property Managers', description: 'Residential property management' },
  { code: '531312', title: 'Nonresidential Property Managers', description: 'Commercial property management' },
  { code: '531320', title: 'Offices of Real Estate Appraisers', description: 'Property appraisal' },
  { code: '531390', title: 'Other Activities Related to Real Estate', description: 'Real estate services' },
  
  // Equipment Rental & Leasing (532XXX)
  { code: '532111', title: 'Passenger Car Rental', description: 'Car rental companies' },
  { code: '532112', title: 'Passenger Car Leasing', description: 'Vehicle leasing' },
  { code: '532120', title: 'Truck, Utility Trailer, and RV (Recreational Vehicle) Rental and Leasing', description: 'Truck rentals' },
  { code: '532210', title: 'Consumer Electronics and Appliances Rental', description: 'Rent-to-own' },
  { code: '532220', title: 'Formal Wear and Costume Rental', description: 'Tuxedo rental' },
  { code: '532230', title: 'Video Tape and Disc Rental', description: 'Video rentals' },
  { code: '532281', title: 'Furniture Rental', description: 'Furniture rental' },
  { code: '532282', title: 'Video Tape and Disc Rental', description: 'Equipment rental' },
  { code: '532283', title: 'Home Health Equipment Rental', description: 'Medical equipment rental' },
  { code: '532284', title: 'Recreational Goods Rental', description: 'Sports equipment rental' },
  { code: '532289', title: 'All Other Consumer Goods Rental', description: 'Other consumer rentals' },
  { code: '532310', title: 'General Rental Centers', description: 'Tool and equipment rental' },
  { code: '532411', title: 'Commercial Air, Rail, and Water Transportation Equipment Rental and Leasing', description: 'Transportation equipment leasing' },
  { code: '532412', title: 'Construction, Mining, and Forestry Machinery and Equipment Rental and Leasing', description: 'Heavy equipment rental' },
  { code: '532420', title: 'Office Machinery and Equipment Rental and Leasing', description: 'Office equipment rental' },
  { code: '532490', title: 'Other Commercial and Industrial Machinery and Equipment Rental and Leasing', description: 'Industrial equipment rental' },
  { code: '533110', title: 'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)', description: 'Patent licensing' },
  
  // Arts, Entertainment, & Recreation (71XXXX)
  { code: '711110', title: 'Theater Companies and Dinner Theaters', description: 'Live theater' },
  { code: '711120', title: 'Dance Companies', description: 'Dance performances' },
  { code: '711130', title: 'Musical Groups and Artists', description: 'Bands, musicians' },
  { code: '711190', title: 'Other Performing Arts Companies', description: 'Circuses, ice shows' },
  { code: '711211', title: 'Sports Teams and Clubs', description: 'Professional sports teams' },
  { code: '711212', title: 'Racetracks', description: 'Auto racing, horse racing' },
  { code: '711219', title: 'Other Spectator Sports', description: 'Sports events' },
  { code: '711310', title: 'Promoters of Performing Arts, Sports, and Similar Events with Facilities', description: 'Event venues' },
  { code: '711320', title: 'Promoters of Performing Arts, Sports, and Similar Events without Facilities', description: 'Event promoters' },
  { code: '711410', title: 'Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures', description: 'Talent agents' },
  { code: '711510', title: 'Independent Artists, Writers, and Performers', description: 'Freelance artists' },
  { code: '712110', title: 'Museums', description: 'Art museums, history museums' },
  { code: '712120', title: 'Historical Sites', description: 'Historic landmarks' },
  { code: '712130', title: 'Zoos and Botanical Gardens', description: 'Zoos, gardens' },
  { code: '712190', title: 'Nature Parks and Other Similar Institutions', description: 'Nature centers' },
  { code: '713110', title: 'Amusement and Theme Parks', description: 'Theme parks' },
  { code: '713120', title: 'Amusement Arcades', description: 'Video arcades' },
  { code: '713210', title: 'Casinos (except Casino Hotels)', description: 'Casinos' },
  { code: '713290', title: 'Other Gambling Industries', description: 'Lottery, bingo' },
  { code: '713910', title: 'Golf Courses and Country Clubs', description: 'Golf facilities' },
  { code: '713920', title: 'Skiing Facilities', description: 'Ski resorts' },
  { code: '713930', title: 'Marinas', description: 'Boat marinas' },
  { code: '713940', title: 'Fitness and Recreational Sports Centers', description: 'Gyms, fitness centers' },
  { code: '713950', title: 'Bowling Centers', description: 'Bowling alleys' },
  { code: '713990', title: 'All Other Amusement and Recreation Industries', description: 'Recreation facilities' },
  
  // Accommodation & Food Services (72XXXX)
  { code: '721110', title: 'Hotels (except Casino Hotels) and Motels', description: 'Hotel industry' },
  { code: '721120', title: 'Casino Hotels', description: 'Casino resorts' },
  { code: '721191', title: 'Bed-and-Breakfast Inns', description: 'B&B lodging' },
  { code: '721199', title: 'All Other Traveler Accommodation', description: 'Other lodging' },
  { code: '721211', title: 'RV (Recreational Vehicle) Parks and Campgrounds', description: 'RV parks, campgrounds' },
  { code: '721214', title: 'Recreational and Vacation Camps (except Campgrounds)', description: 'Summer camps' },
  { code: '721310', title: 'Rooming and Boarding Houses', description: 'Boarding houses' },
  { code: '722310', title: 'Food Service Contractors', description: 'Cafeteria services' },
  { code: '722320', title: 'Caterers', description: 'Catering services' },
  { code: '722330', title: 'Mobile Food Services', description: 'Food trucks' },
  { code: '722410', title: 'Drinking Places (Alcoholic Beverages)', description: 'Bars, taverns' },
  { code: '722511', title: 'Full-Service Restaurants', description: 'Sit-down restaurants' },
  { code: '722513', title: 'Limited-Service Restaurants', description: 'Fast food, quick service' },
  { code: '722514', title: 'Cafeterias, Grill Buffets, and Buffets', description: 'Buffet restaurants' },
  { code: '722515', title: 'Snack and Nonalcoholic Beverage Bars', description: 'Coffee shops, juice bars' },
  
  // Other Services (81XXXX)
  { code: '811111', title: 'General Automotive Repair', description: 'Auto repair shops' },
  { code: '811112', title: 'Automotive Exhaust System Repair', description: 'Muffler shops' },
  { code: '811113', title: 'Automotive Transmission Repair', description: 'Transmission shops' },
  { code: '811118', title: 'Other Automotive Mechanical and Electrical Repair and Maintenance', description: 'Auto service' },
  { code: '811121', title: 'Automotive Body, Paint, and Interior Repair and Maintenance', description: 'Body shops' },
  { code: '811122', title: 'Automotive Glass Replacement Shops', description: 'Auto glass' },
  { code: '811191', title: 'Automotive Oil Change and Lubrication Shops', description: 'Oil change services' },
  { code: '811192', title: 'Car Washes', description: 'Car wash facilities' },
  { code: '811198', title: 'All Other Automotive Repair and Maintenance', description: 'Other auto services' },
  { code: '811211', title: 'Consumer Electronics Repair and Maintenance', description: 'Electronics repair' },
  { code: '811212', title: 'Computer and Office Machine Repair and Maintenance', description: 'Computer repair' },
  { code: '811213', title: 'Communication Equipment Repair and Maintenance', description: 'Phone repair' },
  { code: '811219', title: 'Other Electronic and Precision Equipment Repair and Maintenance', description: 'Equipment repair' },
  { code: '811310', title: 'Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair', description: 'Industrial equipment repair' },
  { code: '811411', title: 'Home and Garden Equipment Repair and Maintenance', description: 'Lawn mower repair' },
  { code: '811412', title: 'Appliance Repair and Maintenance', description: 'Appliance repair' },
  { code: '811420', title: 'Reupholstery and Furniture Repair', description: 'Furniture repair' },
  { code: '811430', title: 'Footwear and Leather Goods Repair', description: 'Shoe repair' },
  { code: '811490', title: 'Other Personal and Household Goods Repair and Maintenance', description: 'Miscellaneous repair' },
  { code: '812111', title: 'Barber Shops', description: 'Barber services' },
  { code: '812112', title: 'Beauty Salons', description: 'Hair salons' },
  { code: '812113', title: 'Nail Salons', description: 'Nail services' },
  { code: '812191', title: 'Diet and Weight Reducing Centers', description: 'Weight loss programs' },
  { code: '812199', title: 'Other Personal Care Services', description: 'Tanning, massage' },
  { code: '812210', title: 'Funeral Homes and Funeral Services', description: 'Funeral services' },
  { code: '812220', title: 'Cemeteries and Crematories', description: 'Cemetery services' },
  { code: '812310', title: 'Coin-Operated Laundries and Drycleaners', description: 'Laundromats' },
  { code: '812320', title: 'Drycleaning and Laundry Services (except Coin-Operated)', description: 'Dry cleaning' },
  { code: '812331', title: 'Linen Supply', description: 'Commercial laundry' },
  { code: '812332', title: 'Industrial Launderers', description: 'Industrial cleaning' },
  { code: '812910', title: 'Pet Care (except Veterinary) Services', description: 'Pet grooming, boarding' },
  { code: '812921', title: 'Photofinishing Laboratories (except One-Hour)', description: 'Photo processing' },
  { code: '812922', title: 'One-Hour Photofinishing', description: 'Quick photo services' },
  { code: '812930', title: 'Parking Lots and Garages', description: 'Parking facilities' },
  { code: '812990', title: 'All Other Personal Services', description: 'Other personal services' },
  
  // Public Administration (92XXXX)
  { code: '921110', title: 'Executive Offices', description: 'Government executive offices' },
  { code: '921120', title: 'Legislative Bodies', description: 'Congress, state legislatures' },
  { code: '921130', title: 'Public Finance Activities', description: 'Tax collection, treasury' },
  { code: '921140', title: 'Executive and Legislative Offices, Combined', description: 'Government offices' },
  { code: '921150', title: 'American Indian and Alaska Native Tribal Governments', description: 'Tribal government' },
  { code: '921190', title: 'Other General Government Support', description: 'Government support' },
  { code: '922110', title: 'Courts', description: 'Court systems' },
  { code: '922120', title: 'Police Protection', description: 'Law enforcement' },
  { code: '922130', title: 'Legal Counsel and Prosecution', description: 'District attorneys' },
  { code: '922140', title: 'Correctional Institutions', description: 'Prisons, jails' },
  { code: '922150', title: 'Parole Offices and Probation Offices', description: 'Probation services' },
  { code: '922160', title: 'Fire Protection', description: 'Fire departments' },
  { code: '922190', title: 'Other Justice, Public Order, and Safety Activities', description: 'Emergency services' },
  { code: '923110', title: 'Administration of Education Programs', description: 'Education departments' },
  { code: '923120', title: 'Administration of Public Health Programs', description: 'Health departments' },
  { code: '923130', title: 'Administration of Human Resource Programs (except Education, Public Health, and Veterans\' Affairs)', description: 'Social services administration' },
  { code: '923140', title: 'Administration of Veterans\' Affairs', description: 'VA administration' },
  { code: '924110', title: 'Administration of Air and Water Resource and Solid Waste Management Programs', description: 'EPA, environmental agencies' },
  { code: '924120', title: 'Administration of Conservation Programs', description: 'Conservation agencies' },
  { code: '925110', title: 'Administration of Housing Programs', description: 'Housing authorities' },
  { code: '925120', title: 'Administration of Urban Planning and Community and Rural Development', description: 'Planning departments' },
  { code: '926110', title: 'Administration of General Economic Programs', description: 'Commerce departments' },
  { code: '926120', title: 'Regulation and Administration of Transportation Programs', description: 'DOT, FAA' },
  { code: '926130', title: 'Regulation and Administration of Communications, Electric, Gas, and Other Utilities', description: 'Utility regulation' },
  { code: '926140', title: 'Regulation of Agricultural Marketing and Commodities', description: 'USDA programs' },
  { code: '926150', title: 'Regulation, Licensing, and Inspection of Miscellaneous Commercial Sectors', description: 'Regulatory agencies' },
  { code: '927110', title: 'Space Research and Technology', description: 'NASA, space programs' },
  { code: '928110', title: 'National Security', description: 'Defense, intelligence' },
  { code: '928120', title: 'International Affairs', description: 'State Department, foreign affairs' },
];

// Helper function to search NAICS codes
export function searchNAICSCodes(searchTerm: string): NAICSCode[] {
  const term = searchTerm.toLowerCase();
  return NAICS_CODES.filter(
    naics =>
      naics.code.includes(searchTerm) ||
      naics.title.toLowerCase().includes(term) ||
      naics.description?.toLowerCase().includes(term)
  );
}

// Helper function to get NAICS code by code
export function getNAICSByCode(code: string): NAICSCode | undefined {
  return NAICS_CODES.find(naics => naics.code === code);
}
