// lib/psc-codes.ts
/**
 * Comprehensive PSC (Product Service Code) Reference
 * Federal Supply Classification System
 * Used for categorizing government contract opportunities
 */

export interface PSCCode {
  code: string;
  title: string;
  category?: string;
  description?: string;
}

export const PSC_CODES: PSCCode[] = [
  // R - Professional, Administrative, and Management Support Services
  { code: 'R', title: 'Professional, Administrative, and Management Support Services', category: 'Professional Services' },
  { code: 'R101', title: 'General Management and Administrative Services', category: 'Professional Services' },
  { code: 'R199', title: 'Other General Management and Administrative Services', category: 'Professional Services' },
  { code: 'R401', title: 'Engineering/Technical Services', category: 'Professional Services', description: 'Engineering design, analysis, consulting' },
  { code: 'R402', title: 'Systems Engineering Services', category: 'Professional Services', description: 'Systems integration, requirements analysis' },
  { code: 'R404', title: 'Research and Development', category: 'Professional Services', description: 'R&D, innovation, prototyping' },
  { code: 'R405', title: 'Mapping, Charting, Geodesy', category: 'Professional Services', description: 'Surveying, GIS, cartography' },
  { code: 'R406', title: 'Technical Assistance', category: 'Professional Services', description: 'Technical support, advisory services' },
  { code: 'R408', title: 'Program Management/Support Services', category: 'Professional Services', description: 'Project management, PMO services' },
  { code: 'R409', title: 'Environmental Services', category: 'Professional Services', description: 'Environmental consulting, compliance' },
  { code: 'R410', title: 'Architect and Engineering Services - General', category: 'Professional Services', description: 'Architectural and engineering services' },
  { code: 'R411', title: 'Support - Professional: Quality Assurance', category: 'Professional Services', description: 'QA, quality control, testing' },
  { code: 'R412', title: 'Support - Professional: Education/Training', category: 'Professional Services', description: 'Training development and delivery' },
  { code: 'R413', title: 'Statistics', category: 'Professional Services', description: 'Statistical analysis, data science' },
  { code: 'R414', title: 'Personnel Services', category: 'Professional Services', description: 'HR consulting, staffing support' },
  { code: 'R415', title: 'Financial and Accounting Services', category: 'Professional Services', description: 'Accounting, auditing, financial analysis' },
  { code: 'R416', title: 'Legal Services', category: 'Professional Services', description: 'Legal counsel, paralegal support' },
  { code: 'R417', title: 'Contract, Procurement, and Acquisition Support', category: 'Professional Services', description: 'Contracting support services' },
  { code: 'R418', title: 'Installation of Equipment', category: 'Professional Services', description: 'Equipment installation services' },
  { code: 'R419', title: 'Support - Professional: Acquisition', category: 'Professional Services', description: 'Acquisition planning and support' },
  { code: 'R420', title: 'Support - Professional: Information Management', category: 'Professional Services', description: 'Records management, data management' },
  { code: 'R421', title: 'Support - Professional: Library Services', category: 'Professional Services', description: 'Library and information services' },
  { code: 'R422', title: 'Support - Professional: Market Research', category: 'Professional Services', description: 'Market analysis, competitive intelligence' },
  { code: 'R423', title: 'Intelligence Services', category: 'Professional Services', description: 'Intelligence analysis, OSINT' },
  { code: 'R424', title: 'Site Preparation and Installation Services', category: 'Professional Services', description: 'Site prep, construction support' },
  { code: 'R425', title: 'Support - Professional: Engineering/Technical', category: 'Professional Services', description: 'Technical and engineering support' },
  { code: 'R426', title: 'Operation of Government-Owned Facility', category: 'Professional Services', description: 'Facility operations and management' },
  { code: 'R497', title: 'Transportation/Travel/Relocation', category: 'Professional Services', description: 'Travel management services' },
  { code: 'R499', title: 'Support - Professional: Other', category: 'Professional Services', description: 'Other professional support services' },
  { code: 'R502', title: 'Support - Management: Contract/Procurement/Acquisition Support', category: 'Professional Services', description: 'Procurement and acquisition management' },
  { code: 'R601', title: 'Guard Services', category: 'Professional Services', description: 'Security guard services' },
  { code: 'R602', title: 'Investigation and Inspection Services', category: 'Professional Services', description: 'Background checks, investigations' },
  { code: 'R603', title: 'Installation Security Services', category: 'Professional Services', description: 'Facility security services' },
  { code: 'R604', title: 'Other Security Services', category: 'Professional Services', description: 'General security services' },
  { code: 'R699', title: 'Custodial/Janitorial Services', category: 'Professional Services', description: 'Cleaning and janitorial' },
  { code: 'R701', title: 'Support - Administrative: Data/Information', category: 'Professional Services', description: 'Data entry, information processing' },
  { code: 'R702', title: 'Support - Administrative: Warehousemen', category: 'Professional Services', description: 'Warehouse management services' },
  { code: 'R703', title: 'Support - Administrative: Public Relations', category: 'Professional Services', description: 'PR, communications, media relations' },
  { code: 'R704', title: 'Support - Administrative: Clerical/Administrative', category: 'Professional Services', description: 'Administrative support services' },
  { code: 'R705', title: 'Support - Administrative: Other', category: 'Professional Services', description: 'Miscellaneous administrative support' },
  { code: 'R706', title: 'Administrative Support Services', category: 'Professional Services', description: 'General administrative services' },
  { code: 'R707', title: 'Library and Archive Services', category: 'Professional Services', description: 'Archival and library services' },
  { code: 'R708', title: 'Funeral Services', category: 'Professional Services', description: 'Mortuary services' },
  { code: 'R799', title: 'Other Administrative Support Services', category: 'Professional Services', description: 'Other admin services' },
  
  // D - Information Technology and Telecommunications
  { code: 'D', title: 'Information Technology and Telecommunications', category: 'IT Services' },
  { code: 'D301', title: 'IT and Telecom - Telecommunications Network Management', category: 'IT Services', description: 'Network operations, NOC services' },
  { code: 'D302', title: 'IT and Telecom - Systems Development Services', category: 'IT Services', description: 'Software development, application development' },
  { code: 'D303', title: 'IT and Telecom - IT and Telecom Operations and Maintenance', category: 'IT Services', description: 'IT support, helpdesk, maintenance' },
  { code: 'D304', title: 'IT and Telecom - IT Facility Operation and Maintenance', category: 'IT Services', description: 'Data center operations' },
  { code: 'D305', title: 'IT and Telecom - IT Backup and Security', category: 'IT Services', description: 'Backup, DR, business continuity' },
  { code: 'D306', title: 'IT and Telecom - IT Services', category: 'IT Services', description: 'General IT services' },
  { code: 'D307', title: 'IT and Telecom - IT Strategy and Architecture', category: 'IT Services', description: 'IT planning, enterprise architecture' },
  { code: 'D308', title: 'IT and Telecom - Programming', category: 'IT Services', description: 'Custom programming, coding services' },
  { code: 'D309', title: 'IT and Telecom - Cloud Computing Services', category: 'IT Services', description: 'Cloud services, SaaS, PaaS, IaaS' },
  { code: 'D310', title: 'IT and Telecom - Cyber Security and Data Backup', category: 'IT Services', description: 'Cybersecurity, infosec, data protection' },
  { code: 'D311', title: 'IT and Telecom - Systems Analysis', category: 'IT Services', description: 'Business analysis, systems analysis' },
  { code: 'D312', title: 'IT and Telecom - IT Education and Training', category: 'IT Services', description: 'IT training, certification programs' },
  { code: 'D313', title: 'IT and Telecom - Data Conversion', category: 'IT Services', description: 'Data migration, format conversion' },
  { code: 'D314', title: 'IT and Telecom - Digitizing', category: 'IT Services', description: 'Document scanning, digitization' },
  { code: 'D315', title: 'IT and Telecom - PC/LAN/WAN Support', category: 'IT Services', description: 'Desktop support, network support' },
  { code: 'D316', title: 'IT and Telecom - Network Installation, Maintenance and Repair', category: 'IT Services', description: 'Network infrastructure services' },
  { code: 'D317', title: 'IT and Telecom - Web-based Subscription Services', category: 'IT Services', description: 'SaaS, subscription platforms' },
  { code: 'D318', title: 'IT and Telecom - IT Software Licenses', category: 'IT Services', description: 'Software licensing, maintenance' },
  { code: 'D319', title: 'IT and Telecom - Artificial Intelligence and Machine Learning', category: 'IT Services', description: 'AI/ML services, data science' },
  { code: 'D320', title: 'IT and Telecom - Data Management', category: 'IT Services', description: 'Database management, data warehousing' },
  { code: 'D321', title: 'IT and Telecom - Internet of Things (IoT)', category: 'IT Services', description: 'IoT solutions and services' },
  { code: 'D322', title: 'IT and Telecom - Blockchain Services', category: 'IT Services', description: 'Blockchain development and consulting' },
  { code: 'D399', title: 'IT and Telecom - Other IT and Telecommunications', category: 'IT Services', description: 'Other IT services' },
  
  // C - Architect and Engineering Services - Construction
  { code: 'C', title: 'Architect and Engineering Services - Construction', category: 'Construction Services' },
  { code: 'C111', title: 'Architect and Engineering - Architect Services: Site Planning and Design', category: 'Construction Services', description: 'Architectural design and planning' },
  { code: 'C112', title: 'Architect and Engineering - Architect Services: Structural Engineering', category: 'Construction Services', description: 'Structural design and analysis' },
  { code: 'C113', title: 'Architect and Engineering - Architect Services: Mechanical Engineering', category: 'Construction Services', description: 'HVAC, plumbing engineering' },
  { code: 'C114', title: 'Architect and Engineering - Architect Services: Electrical Engineering', category: 'Construction Services', description: 'Electrical systems design' },
  { code: 'C115', title: 'Architect and Engineering - Architect Services: Civil Engineering', category: 'Construction Services', description: 'Civil engineering services' },
  { code: 'C119', title: 'Architect and Engineering - Other Architect Services', category: 'Construction Services', description: 'Other architectural services' },
  { code: 'C121', title: 'Architect and Engineering - Engineering Services: Structural Engineering', category: 'Construction Services', description: 'Structural engineering design' },
  { code: 'C122', title: 'Architect and Engineering - Engineering Services: Mechanical Engineering', category: 'Construction Services', description: 'Mechanical engineering services' },
  { code: 'C123', title: 'Architect and Engineering - Engineering Services: Electrical Engineering', category: 'Construction Services', description: 'Electrical engineering design' },
  { code: 'C124', title: 'Architect and Engineering - Engineering Services: Civil Engineering', category: 'Construction Services', description: 'Civil engineering design' },
  { code: 'C125', title: 'Architect and Engineering - Engineering Services: Environmental Engineering', category: 'Construction Services', description: 'Environmental engineering services' },
  { code: 'C129', title: 'Architect and Engineering - Other Engineering Services', category: 'Construction Services', description: 'Other engineering services' },
  { code: 'C211', title: 'Architect and Engineering - Construction/Building Services', category: 'Construction Services', description: 'General construction services' },
  { code: 'C212', title: 'Architect and Engineering - Design of Buildings', category: 'Construction Services', description: 'Building design services' },
  { code: 'C213', title: 'Architect and Engineering - Design of Structures and Facilities', category: 'Construction Services', description: 'Facility design and planning' },
  { code: 'C214', title: 'Architect and Engineering - Interior Design Services', category: 'Construction Services', description: 'Interior space planning' },
  { code: 'C215', title: 'Architect and Engineering - Landscape Architecture', category: 'Construction Services', description: 'Landscape design services' },
  { code: 'C219', title: 'Architect and Engineering - Other Construction and Building Services', category: 'Construction Services', description: 'Other construction services' },
  
  // J - Maintenance, Repair, and Rebuilding of Equipment
  { code: 'J', title: 'Maintenance, Repair, and Rebuilding of Equipment', category: 'Maintenance Services' },
  { code: 'J001', title: 'Maintenance/Repair/Rebuild of Aircraft and Airframe Structural Components', category: 'Maintenance Services', description: 'Aircraft maintenance' },
  { code: 'J002', title: 'Maintenance/Repair of Aircraft Components and Accessories', category: 'Maintenance Services', description: 'Aircraft parts repair' },
  { code: 'J003', title: 'Maintenance/Repair of Aircraft Engines and Engine Parts', category: 'Maintenance Services', description: 'Engine maintenance' },
  { code: 'J011', title: 'Maintenance/Repair of Ships', category: 'Maintenance Services', description: 'Ship repair and maintenance' },
  { code: 'J012', title: 'Maintenance/Repair of Ship and Marine Equipment', category: 'Maintenance Services', description: 'Marine equipment repair' },
  { code: 'J015', title: 'Maintenance/Repair/Rebuild of Aircraft', category: 'Maintenance Services', description: 'Complete aircraft maintenance' },
  { code: 'J016', title: 'Maintenance/Repair of Engines, Turbines, and Components', category: 'Maintenance Services', description: 'Engine repair services' },
  { code: 'J017', title: 'Maintenance/Repair of Mechanical Equipment', category: 'Maintenance Services', description: 'Mechanical equipment maintenance' },
  { code: 'J018', title: 'Maintenance/Repair of Vehicles', category: 'Maintenance Services', description: 'Vehicle maintenance and repair' },
  { code: 'J019', title: 'Maintenance/Repair/Rebuild of Ships', category: 'Maintenance Services', description: 'Ship overhaul and repair' },
  { code: 'J020', title: 'Maintenance/Repair of Weapons', category: 'Maintenance Services', description: 'Weapons systems maintenance' },
  { code: 'J021', title: 'Maintenance/Repair of Ammunition and Explosives', category: 'Maintenance Services', description: 'Ordnance maintenance' },
  { code: 'J022', title: 'Maintenance/Repair of Guided Missiles', category: 'Maintenance Services', description: 'Missile systems maintenance' },
  { code: 'J030', title: 'Maintenance/Repair of Instruments and Laboratory Equipment', category: 'Maintenance Services', description: 'Scientific equipment repair' },
  { code: 'J031', title: 'Maintenance/Repair of Photographic Equipment', category: 'Maintenance Services', description: 'Camera and photo equipment repair' },
  { code: 'J032', title: 'Maintenance/Repair of Medical, Dental, and Veterinary Equipment', category: 'Maintenance Services', description: 'Medical equipment maintenance' },
  { code: 'J033', title: 'Maintenance/Repair of Optical Instruments', category: 'Maintenance Services', description: 'Optical equipment repair' },
  { code: 'J034', title: 'Maintenance/Repair of ADP and Office Equipment', category: 'Maintenance Services', description: 'IT and office equipment repair' },
  { code: 'J036', title: 'Maintenance/Repair/Rebuild of Engines, Turbines, and Components', category: 'Maintenance Services', description: 'Power systems maintenance' },
  { code: 'J038', title: 'Maintenance/Repair of Construction, Mining, Excavating, and Highway Maintenance Equipment', category: 'Maintenance Services', description: 'Heavy equipment maintenance' },
  { code: 'J039', title: 'Maintenance/Repair of Materials Handling Equipment', category: 'Maintenance Services', description: 'Forklift and handling equipment repair' },
  { code: 'J041', title: 'Maintenance/Repair of Facilities', category: 'Maintenance Services', description: 'Building maintenance and repair' },
  { code: 'J042', title: 'Maintenance/Repair of Grounds', category: 'Maintenance Services', description: 'Grounds maintenance, landscaping' },
  { code: 'J043', title: 'Maintenance/Repair of Vehicles', category: 'Maintenance Services', description: 'Fleet maintenance services' },
  { code: 'J044', title: 'Maintenance/Repair of HVAC Equipment', category: 'Maintenance Services', description: 'HVAC maintenance and repair' },
  { code: 'J045', title: 'Maintenance/Repair of Plumbing Equipment', category: 'Maintenance Services', description: 'Plumbing repair services' },
  { code: 'J046', title: 'Maintenance/Repair of Electrical Equipment', category: 'Maintenance Services', description: 'Electrical systems maintenance' },
  { code: 'J047', title: 'Maintenance/Repair of Fire Protection Systems', category: 'Maintenance Services', description: 'Fire system maintenance' },
  { code: 'J050', title: 'Maintenance/Repair of Furniture', category: 'Maintenance Services', description: 'Furniture repair services' },
  { code: 'J060', title: 'Maintenance/Repair of Textiles, Clothing, and Footwear', category: 'Maintenance Services', description: 'Textile and garment repair' },
  { code: 'J070', title: 'Maintenance/Repair/Rebuild of Engines, Turbines, and Components', category: 'Maintenance Services', description: 'Engine overhaul services' },
  { code: 'J998', title: 'Maintenance/Repair of Equipment - Electrical and Electronic', category: 'Maintenance Services', description: 'Electronics maintenance' },
  { code: 'J999', title: 'Maintenance/Repair of Equipment - General', category: 'Maintenance Services', description: 'General equipment maintenance' },
  
  // S - Utilities and Housekeeping Services
  { code: 'S', title: 'Utilities and Housekeeping Services', category: 'Facility Services' },
  { code: 'S101', title: 'Utilities - Electric', category: 'Facility Services', description: 'Electrical utility services' },
  { code: 'S102', title: 'Utilities - Gas', category: 'Facility Services', description: 'Natural gas services' },
  { code: 'S103', title: 'Utilities - Water', category: 'Facility Services', description: 'Water and sewer services' },
  { code: 'S104', title: 'Utilities - Steam', category: 'Facility Services', description: 'Steam heating services' },
  { code: 'S105', title: 'Utilities - Chilled Water', category: 'Facility Services', description: 'Chilled water services' },
  { code: 'S106', title: 'Utilities - Compressed Air', category: 'Facility Services', description: 'Compressed air services' },
  { code: 'S199', title: 'Utilities - Other', category: 'Facility Services', description: 'Other utility services' },
  { code: 'S201', title: 'Housekeeping - Facilities Operations Support', category: 'Facility Services', description: 'Facility operations services' },
  { code: 'S202', title: 'Housekeeping - Cleaning/Janitorial', category: 'Facility Services', description: 'Janitorial and cleaning services' },
  { code: 'S203', title: 'Housekeeping - Trash/Garbage Collection and Disposal Services', category: 'Facility Services', description: 'Waste removal services' },
  { code: 'S204', title: 'Housekeeping - Reclamation Services', category: 'Facility Services', description: 'Recycling and waste recovery' },
  { code: 'S205', title: 'Housekeeping - Laundry and Dry Cleaning', category: 'Facility Services', description: 'Laundry services' },
  { code: 'S206', title: 'Housekeeping - Interior Plantscaping', category: 'Facility Services', description: 'Indoor plant services' },
  { code: 'S207', title: 'Housekeeping - Pest Control Services', category: 'Facility Services', description: 'Extermination and pest management' },
  { code: 'S208', title: 'Housekeeping - Window Cleaning', category: 'Facility Services', description: 'Window washing services' },
  { code: 'S209', title: 'Housekeeping - Other', category: 'Facility Services', description: 'Other housekeeping services' },
  { code: 'S210', title: 'Food Services - Institutional', category: 'Facility Services', description: 'Cafeteria and food services' },
  { code: 'S211', title: 'Facility Management/Operation/Maintenance', category: 'Facility Services', description: 'Comprehensive facility management' },
  { code: 'S212', title: 'Facilities Engineering and Technical Services', category: 'Facility Services', description: 'Engineering support for facilities' },
  { code: 'S213', title: 'Facilities - Protective Services', category: 'Facility Services', description: 'Security and protection services' },
  { code: 'S214', title: 'Facilities - Logistics Support', category: 'Facility Services', description: 'Facility logistics services' },
  { code: 'S215', title: 'Facilities - Concession Services', category: 'Facility Services', description: 'Vending and concession services' },
  { code: 'S216', title: 'Land and Premises Maintenance and Repair', category: 'Facility Services', description: 'Grounds and building maintenance' },
  { code: 'S217', title: 'Building Demolition', category: 'Facility Services', description: 'Demolition services' },
  { code: 'S218', title: 'Snow Removal', category: 'Facility Services', description: 'Snow and ice removal' },
  { code: 'S299', title: 'Other Housekeeping Services', category: 'Facility Services', description: 'Miscellaneous housekeeping' },
  
  // T - Photo, Mapping, Printing, and Publication Services
  { code: 'T', title: 'Photo, Mapping, Printing, and Publication Services', category: 'Publishing Services' },
  { code: 'T001', title: 'Photo/Map/Print - General Photography', category: 'Publishing Services', description: 'Photography services' },
  { code: 'T002', title: 'Photo/Map/Print - Motion Picture/Video Production', category: 'Publishing Services', description: 'Video production services' },
  { code: 'T003', title: 'Photo/Map/Print - Audio Recording', category: 'Publishing Services', description: 'Audio production services' },
  { code: 'T004', title: 'Photo/Map/Print - Aerial Photography', category: 'Publishing Services', description: 'Aerial imaging services' },
  { code: 'T005', title: 'Photo/Map/Print - Photogrammetric Services', category: 'Publishing Services', description: 'Photogrammetry and mapping' },
  { code: 'T006', title: 'Photo/Map/Print - Cartographic Services', category: 'Publishing Services', description: 'Map making services' },
  { code: 'T007', title: 'Photo/Map/Print - Surveying Services', category: 'Publishing Services', description: 'Land surveying' },
  { code: 'T008', title: 'Photo/Map/Print - Charting Services', category: 'Publishing Services', description: 'Navigation charts' },
  { code: 'T009', title: 'Photo/Map/Print - Geodetic Surveying', category: 'Publishing Services', description: 'Geodetic services' },
  { code: 'T010', title: 'Photo/Map/Print - Hydrographic Surveying', category: 'Publishing Services', description: 'Marine surveying' },
  { code: 'T011', title: 'Photo/Map/Print - Printing and Reproduction', category: 'Publishing Services', description: 'Printing services' },
  { code: 'T012', title: 'Photo/Map/Print - Lithography', category: 'Publishing Services', description: 'Lithographic printing' },
  { code: 'T013', title: 'Photo/Map/Print - Offset Printing', category: 'Publishing Services', description: 'Offset printing services' },
  { code: 'T014', title: 'Photo/Map/Print - Digital Printing', category: 'Publishing Services', description: 'Digital printing' },
  { code: 'T015', title: 'Photo/Map/Print - Screen Printing', category: 'Publishing Services', description: 'Screen printing services' },
  { code: 'T016', title: 'Photo/Map/Print - Photogrammetric Services', category: 'Publishing Services', description: '3D modeling from photos' },
  { code: 'T017', title: 'Photo/Map/Print - Publication Services', category: 'Publishing Services', description: 'Publishing and editing' },
  { code: 'T018', title: 'Photo/Map/Print - Graphic Design', category: 'Publishing Services', description: 'Graphic design services' },
  { code: 'T019', title: 'Photo/Map/Print - Illustrative Services', category: 'Publishing Services', description: 'Illustration and artwork' },
  { code: 'T099', title: 'Photo/Map/Print - Other', category: 'Publishing Services', description: 'Other photo/print services' },
  
  // U - Education and Training Services
  { code: 'U', title: 'Education and Training Services', category: 'Training Services' },
  { code: 'U001', title: 'Education/Training - Primary and Secondary', category: 'Training Services', description: 'K-12 education services' },
  { code: 'U002', title: 'Education/Training - Higher Education', category: 'Training Services', description: 'College and university education' },
  { code: 'U003', title: 'Education/Training - Vocational/Technical', category: 'Training Services', description: 'Vocational training programs' },
  { code: 'U004', title: 'Education/Training - Professional Development', category: 'Training Services', description: 'Professional training and certifications' },
  { code: 'U005', title: 'Education/Training - Management Development', category: 'Training Services', description: 'Leadership and management training' },
  { code: 'U006', title: 'Education/Training - Computer Training', category: 'Training Services', description: 'IT and software training' },
  { code: 'U007', title: 'Education/Training - Language Training', category: 'Training Services', description: 'Foreign language instruction' },
  { code: 'U008', title: 'Education/Training - Flight Training', category: 'Training Services', description: 'Pilot and aviation training' },
  { code: 'U009', title: 'Education/Training - Other', category: 'Training Services', description: 'Other educational services' },
  { code: 'U010', title: 'Education/Training - Curriculum Development', category: 'Training Services', description: 'Course design and development' },
  { code: 'U011', title: 'Education/Training - Instructional Design', category: 'Training Services', description: 'Learning design services' },
  { code: 'U012', title: 'Education/Training - E-Learning Development', category: 'Training Services', description: 'Online training development' },
  { code: 'U013', title: 'Education/Training - Training Delivery', category: 'Training Services', description: 'Instructor-led training' },
  { code: 'U014', title: 'Education/Training - Simulation Training', category: 'Training Services', description: 'Simulator-based training' },
  { code: 'U015', title: 'Education/Training - Educational Technology', category: 'Training Services', description: 'EdTech solutions' },
  { code: 'U099', title: 'Education/Training - Other Educational Services', category: 'Training Services', description: 'Other training services' },
  
  // V - Transportation, Travel, and Relocation Services
  { code: 'V', title: 'Transportation, Travel, and Relocation Services', category: 'Transportation Services' },
  { code: 'V111', title: 'Air Transportation: Freight', category: 'Transportation Services', description: 'Air cargo services' },
  { code: 'V112', title: 'Air Transportation: Passenger', category: 'Transportation Services', description: 'Passenger air transport' },
  { code: 'V121', title: 'Motor Pool Operations', category: 'Transportation Services', description: 'Fleet management services' },
  { code: 'V122', title: 'Vehicular Equipment Rental', category: 'Transportation Services', description: 'Vehicle rental services' },
  { code: 'V131', title: 'Freight Transportation: Truck', category: 'Transportation Services', description: 'Trucking services' },
  { code: 'V132', title: 'Freight Transportation: Rail', category: 'Transportation Services', description: 'Rail freight services' },
  { code: 'V211', title: 'Water Transportation: Freight', category: 'Transportation Services', description: 'Marine cargo transport' },
  { code: 'V212', title: 'Water Transportation: Passenger', category: 'Transportation Services', description: 'Passenger water transport' },
  { code: 'V213', title: 'Water Transportation: Vessels', category: 'Transportation Services', description: 'Ship chartering' },
  { code: 'V301', title: 'Travel and Lodging Services', category: 'Transportation Services', description: 'Travel agency services' },
  { code: 'V302', title: 'Relocation Services', category: 'Transportation Services', description: 'Employee relocation services' },
  { code: 'V303', title: 'Household Goods Moving and Storage', category: 'Transportation Services', description: 'Moving and storage services' },
  { code: 'V304', title: 'Freight Forwarding', category: 'Transportation Services', description: 'Freight forwarding services' },
  { code: 'V305', title: 'Cargo Handling', category: 'Transportation Services', description: 'Cargo loading and unloading' },
  { code: 'V306', title: 'Warehousing and Distribution', category: 'Transportation Services', description: 'Warehouse services' },
  { code: 'V399', title: 'Other Transportation Services', category: 'Transportation Services', description: 'Miscellaneous transport services' },
  
  // W - Lease or Rental of Equipment
  { code: 'W', title: 'Lease or Rental of Equipment', category: 'Equipment Rental' },
  { code: 'W011', title: 'Lease/Rental of Aircraft', category: 'Equipment Rental', description: 'Aircraft leasing' },
  { code: 'W012', title: 'Lease/Rental of Engines, Turbines and Components', category: 'Equipment Rental', description: 'Engine rentals' },
  { code: 'W021', title: 'Lease/Rental of Weapons', category: 'Equipment Rental', description: 'Weapons system leasing' },
  { code: 'W031', title: 'Lease/Rental of Electrical and Electronic Equipment', category: 'Equipment Rental', description: 'Electronics rental' },
  { code: 'W041', title: 'Lease/Rental of ADP Equipment/Software', category: 'Equipment Rental', description: 'Computer equipment rental' },
  { code: 'W051', title: 'Lease/Rental of Construction Equipment', category: 'Equipment Rental', description: 'Heavy equipment rental' },
  { code: 'W061', title: 'Lease/Rental of Medical Equipment', category: 'Equipment Rental', description: 'Medical equipment leasing' },
  { code: 'W071', title: 'Lease/Rental of Office Furniture and Equipment', category: 'Equipment Rental', description: 'Office equipment rental' },
  { code: 'W072', title: 'Lease/Rental of Vessels', category: 'Equipment Rental', description: 'Ship and boat leasing' },
  { code: 'W073', title: 'Lease/Rental of Railroad Equipment', category: 'Equipment Rental', description: 'Rail equipment leasing' },
  { code: 'W074', title: 'Lease/Rental of Vehicles', category: 'Equipment Rental', description: 'Vehicle leasing services' },
  { code: 'W081', title: 'Lease/Rental of Audiovisual Equipment', category: 'Equipment Rental', description: 'AV equipment rental' },
  { code: 'W091', title: 'Lease/Rental of Miscellaneous Equipment', category: 'Equipment Rental', description: 'Other equipment rentals' },
  { code: 'W099', title: 'Lease/Rental of Equipment - Other', category: 'Equipment Rental', description: 'Other rentals' },
  
  // Y - Construction of Structures and Facilities
  { code: 'Y', title: 'Construction of Structures and Facilities', category: 'Construction' },
  { code: 'Y1AA', title: 'Construction - Airfield Lighting', category: 'Construction', description: 'Runway and airfield lighting installation' },
  { code: 'Y1AB', title: 'Construction - Airfield Pavements', category: 'Construction', description: 'Runway and taxiway construction' },
  { code: 'Y1AC', title: 'Construction - Airfield Structures', category: 'Construction', description: 'Hangars, terminal buildings' },
  { code: 'Y1BA', title: 'Construction - Communication Systems', category: 'Construction', description: 'Telecom infrastructure' },
  { code: 'Y1BB', title: 'Construction - Electrical Systems', category: 'Construction', description: 'Electrical construction' },
  { code: 'Y1CA', title: 'Construction - Streets, Roads, and Parking', category: 'Construction', description: 'Road and parking construction' },
  { code: 'Y1CB', title: 'Construction - Bridges and Overpasses', category: 'Construction', description: 'Bridge construction' },
  { code: 'Y1CC', title: 'Construction - Tunnels and Subways', category: 'Construction', description: 'Underground construction' },
  { code: 'Y1DA', title: 'Construction - Buildings', category: 'Construction', description: 'Building construction' },
  { code: 'Y1DB', title: 'Construction - Warehouses', category: 'Construction', description: 'Warehouse construction' },
  { code: 'Y1DC', title: 'Construction - Administrative Buildings', category: 'Construction', description: 'Office building construction' },
  { code: 'Y1DD', title: 'Construction - Housing', category: 'Construction', description: 'Residential construction' },
  { code: 'Y1DE', title: 'Construction - Hospitals and Medical Facilities', category: 'Construction', description: 'Healthcare facility construction' },
  { code: 'Y1DF', title: 'Construction - Educational Facilities', category: 'Construction', description: 'School construction' },
  { code: 'Y1EA', title: 'Construction - Utilities', category: 'Construction', description: 'Utility infrastructure construction' },
  { code: 'Y1EB', title: 'Construction - Water Treatment Plants', category: 'Construction', description: 'Water facility construction' },
  { code: 'Y1EC', title: 'Construction - Wastewater Treatment', category: 'Construction', description: 'Sewer plant construction' },
  { code: 'Y1ED', title: 'Construction - Power Generation Facilities', category: 'Construction', description: 'Power plant construction' },
  { code: 'Y1FA', title: 'Construction - Dams and Reservoirs', category: 'Construction', description: 'Dam construction' },
  { code: 'Y1FB', title: 'Construction - Harbors and Piers', category: 'Construction', description: 'Marine facility construction' },
  { code: 'Y1FC', title: 'Construction - Flood Control', category: 'Construction', description: 'Flood control infrastructure' },
  { code: 'Y1GA', title: 'Construction - Industrial Buildings', category: 'Construction', description: 'Factory construction' },
  { code: 'Y1GB', title: 'Construction - Manufacturing Facilities', category: 'Construction', description: 'Manufacturing plant construction' },
  { code: 'Y1ZZ', title: 'Construction - Other Structures and Facilities', category: 'Construction', description: 'Other construction projects' },
  
  // Z - Maintenance, Repair, or Alteration of Real Property
  { code: 'Z', title: 'Maintenance, Repair, or Alteration of Real Property', category: 'Property Maintenance' },
  { code: 'Z1AA', title: 'Maintenance/Repair - Electrical and Mechanical Systems', category: 'Property Maintenance', description: 'Building systems maintenance' },
  { code: 'Z1AB', title: 'Maintenance/Repair - HVAC Systems', category: 'Property Maintenance', description: 'HVAC maintenance' },
  { code: 'Z1AC', title: 'Maintenance/Repair - Plumbing Systems', category: 'Property Maintenance', description: 'Plumbing maintenance' },
  { code: 'Z1AD', title: 'Maintenance/Repair - Roofing', category: 'Property Maintenance', description: 'Roof repair and maintenance' },
  { code: 'Z1BA', title: 'Maintenance/Repair - Pavement Maintenance', category: 'Property Maintenance', description: 'Road and parking lot maintenance' },
  { code: 'Z1BB', title: 'Maintenance/Repair - Roads and Parking', category: 'Property Maintenance', description: 'Pavement maintenance' },
  { code: 'Z1CA', title: 'Maintenance/Repair - Grounds Maintenance', category: 'Property Maintenance', description: 'Landscaping and grounds care' },
  { code: 'Z1CB', title: 'Maintenance/Repair - Lawn and Garden', category: 'Property Maintenance', description: 'Lawn care services' },
  { code: 'Z1DA', title: 'Maintenance/Repair - Buildings and Structures', category: 'Property Maintenance', description: 'Building maintenance' },
  { code: 'Z1DB', title: 'Maintenance/Repair - Interior Finishes', category: 'Property Maintenance', description: 'Interior maintenance' },
  { code: 'Z1DC', title: 'Maintenance/Repair - Exterior Finishes', category: 'Property Maintenance', description: 'Exterior building maintenance' },
  { code: 'Z1EA', title: 'Maintenance/Repair - Utilities', category: 'Property Maintenance', description: 'Utility system maintenance' },
  { code: 'Z1FA', title: 'Maintenance/Repair - Fencing and Gates', category: 'Property Maintenance', description: 'Fence repair and maintenance' },
  { code: 'Z1GA', title: 'Maintenance/Repair - Fire Protection Systems', category: 'Property Maintenance', description: 'Fire system maintenance' },
  { code: 'Z1HA', title: 'Maintenance/Repair - Security Systems', category: 'Property Maintenance', description: 'Security system maintenance' },
  { code: 'Z2AA', title: 'Renovation/Alteration - Buildings', category: 'Property Maintenance', description: 'Building renovation' },
  { code: 'Z2AB', title: 'Renovation/Alteration - Interior Spaces', category: 'Property Maintenance', description: 'Interior renovation' },
  { code: 'Z2AC', title: 'Renovation/Alteration - Exterior Improvements', category: 'Property Maintenance', description: 'Exterior upgrades' },
  { code: 'Z2BA', title: 'Renovation/Alteration - Accessibility Improvements', category: 'Property Maintenance', description: 'ADA compliance upgrades' },
  { code: 'Z2CA', title: 'Renovation/Alteration - Energy Efficiency Improvements', category: 'Property Maintenance', description: 'Energy efficiency upgrades' },
  { code: 'Z2ZZ', title: 'Maintenance/Repair - Other Real Property', category: 'Property Maintenance', description: 'Other property maintenance' },
  
  // Additional Common PSC Codes
  { code: 'A', title: 'Research and Development', category: 'R&D Services', description: 'Research and development services' },
  { code: 'B', title: 'Special Studies and Analyses - Not R&D', category: 'Analysis Services', description: 'Studies, analysis, and consulting' },
  { code: 'F', title: 'Natural Resources and Conservation Services', category: 'Environmental Services', description: 'Environmental and conservation services' },
  { code: 'G', title: 'Social Services', category: 'Social Services', description: 'Social and human services' },
  { code: 'H', title: 'Quality Control, Testing, and Inspection Services', category: 'QA Services', description: 'Testing and inspection services' },
  { code: 'K', title: 'Medical Services', category: 'Healthcare Services', description: 'Medical and healthcare services' },
  { code: 'L', title: 'Technical Representative Services', category: 'Technical Services', description: 'Technical representation services' },
  { code: 'M', title: 'Operation of Government-Owned Facilities', category: 'Facility Operations', description: 'Government facility operations' },
  { code: 'N', title: 'Installation of Equipment', category: 'Installation Services', description: 'Equipment installation services' },
  { code: 'P', title: 'Salvage Services', category: 'Salvage Services', description: 'Salvage and recovery services' },
  { code: 'Q', title: 'Medical Charges', category: 'Medical Services', description: 'Medical billing and charges' },
];

// Helper function to search PSC codes
export function searchPSCCodes(searchTerm: string): PSCCode[] {
  const term = searchTerm.toLowerCase();
  return PSC_CODES.filter(
    psc =>
      psc.code.toLowerCase().includes(term) ||
      psc.title.toLowerCase().includes(term) ||
      psc.category?.toLowerCase().includes(term) ||
      psc.description?.toLowerCase().includes(term)
  );
}

// Helper function to get PSC code by code
export function getPSCByCode(code: string): PSCCode | undefined {
  return PSC_CODES.find(psc => psc.code === code);
}

// Helper function to get PSC codes by category
export function getPSCsByCategory(category: string): PSCCode[] {
  return PSC_CODES.filter(psc => psc.category === category);
}